export interface Currency {
    code: string;
    symbol: string;
    name: string;
}

export const currencies: Currency[] = [
    // Major currencies
    { code: 'GBP', symbol: '£', name: 'British Pound Sterling' },
    { code: 'USD', symbol: '$', name: 'United States Dollar' },
    { code: 'EUR', symbol: '€', name: 'Euro' },
    { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
    { code: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
    { code: 'CAD', symbol: '$', name: 'Canadian Dollar' },
    { code: 'AUD', symbol: '$', name: 'Australian Dollar' },
    { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc' },
    { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
    { code: 'NZD', symbol: '$', name: 'New Zealand Dollar' },
    // Other widely used currencies
    { code: 'HKD', symbol: '$', name: 'Hong Kong Dollar' },
    { code: 'SGD', symbol: '$', name: 'Singapore Dollar' },
    { code: 'KRW', symbol: '₩', name: 'South Korean Won' },
    { code: 'SEK', symbol: 'kr', name: 'Swedish Krona' },
    { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone' },
    { code: 'DKK', symbol: 'kr', name: 'Danish Krone' },
    { code: 'PLN', symbol: 'zł', name: 'Polish Zloty' },
    { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna' },
    { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint' },
    { code: 'TRY', symbol: '₺', name: 'Turkish Lira' },
    { code: 'ZAR', symbol: 'R', name: 'South African Rand' },
    { code: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
    { code: 'MXN', symbol: '$', name: 'Mexican Peso' },
    { code: 'ILS', symbol: '₪', name: 'Israeli New Shekel' },
    { code: 'AED', symbol: 'د.إ', name: 'United Arab Emirates Dirham' },
    { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal' },
    { code: 'THB', symbol: '฿', name: 'Thai Baht' },
    { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
    { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah' },
    { code: 'PHP', symbol: '₱', name: 'Philippine Peso' },
    // Europe
    { code: 'ISK', symbol: 'kr', name: 'Icelandic Króna' },
    { code: 'RON', symbol: 'lei', name: 'Romanian Leu' },
    { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev' },
    { code: 'RSD', symbol: 'дин.', name: 'Serbian Dinar' },
    { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia' },
    { code: 'RUB', symbol: '₽', name: 'Russian Ruble' },
    { code: 'GEL', symbol: '₾', name: 'Georgian Lari' },
    { code: 'AMD', symbol: '֏', name: 'Armenian Dram' },
    { code: 'AZN', symbol: '₼', name: 'Azerbaijani Manat' },
    { code: 'ALL', symbol: 'Lek', name: 'Albanian Lek' },
    { code: 'BAM', symbol: 'KM', name: 'Bosnia-Herzegovina Convertible Mark' },
    { code: 'MDL', symbol: 'L', name: 'Moldovan Leu' },
    { code: 'MKD', symbol: 'ден', name: 'Macedonian Denar' },
    // Americas
    { code: 'ARS', symbol: '$', name: 'Argentine Peso' },
    { code: 'CLP', symbol: '$', name: 'Chilean Peso' },
    { code: 'COP', symbol: '$', name: 'Colombian Peso' },
    { code: 'PEN', symbol: 'S/.', name: 'Peruvian Sol' },
    { code: 'UYU', symbol: '$U', name: 'Uruguayan Peso' },
    { code: 'CRC', symbol: '₡', name: 'Costa Rican Colón' },
    { code: 'DOP', symbol: 'RD$', name: 'Dominican Peso' },
    { code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal' },
    { code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa' },
    { code: 'PYG', symbol: '₲', name: 'Paraguayan Guarani' },
    { code: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano' },
    { code: 'NIO', symbol: 'C$', name: 'Nicaraguan Córdoba' },
    { code: 'JMD', symbol: 'J$', name: 'Jamaican Dollar' },
    { code: 'TTD', symbol: 'TT$', name: 'Trinidad and Tobago Dollar' },
    { code: 'BSD', symbol: '$', name: 'Bahamian Dollar' },
    { code: 'BBD', symbol: '$', name: 'Barbadian Dollar' },
    { code: 'BZD', symbol: 'BZ$', name: 'Belize Dollar' },
    { code: 'XCD', symbol: '$', name: 'East Caribbean Dollar' },
    // Middle East
    { code: 'QAR', symbol: 'ر.ق', name: 'Qatari Riyal' },
    { code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar' },
    { code: 'BHD', symbol: '.د.ب', name: 'Bahraini Dinar' },
    { code: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial' },
    { code: 'JOD', symbol: 'د.ا', name: 'Jordanian Dinar' },
    { code: 'EGP', symbol: '£', name: 'Egyptian Pound' },
    { code: 'MAD', symbol: 'د.م.', name: 'Moroccan Dirham' },
    { code: 'TND', symbol: 'د.ت', name: 'Tunisian Dinar' },
    { code: 'DZD', symbol: 'دج', name: 'Algerian Dinar' },
    { code: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar' },
    { code: 'IRR', symbol: '﷼', name: 'Iranian Rial' },
    { code: 'LBP', symbol: '£', name: 'Lebanese Pound' },
    { code: 'YER', symbol: '﷼', name: 'Yemeni Rial' },

    // Asia
    { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee' },
    { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka' },
    { code: 'LKR', symbol: '₨', name: 'Sri Lankan Rupee' },
    { code: 'NPR', symbol: '₨', name: 'Nepalese Rupee' },
    { code: 'AFN', symbol: '؋', name: 'Afghan Afghani' },
    { code: 'VND', symbol: '₫', name: 'Vietnamese Dong' },
    { code: 'MMK', symbol: 'K', name: 'Myanmar Kyat' },
    { code: 'KHR', symbol: '៛', name: 'Cambodian Riel' },
    { code: 'LAK', symbol: '₭', name: 'Lao Kip' },
    { code: 'MNT', symbol: '₮', name: 'Mongolian Tögrög' },
    { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge' },
    { code: 'KGS', symbol: 'с', name: 'Kyrgyzstani Som' },
    { code: 'UZS', symbol: 'лв', name: 'Uzbekistani Som' },
    { code: 'TJS', symbol: 'SM', name: 'Tajikistani Somoni' },
    { code: 'TMT', symbol: 'm', name: 'Turkmenistani Manat' },
    // Africa
    { code: 'NGN', symbol: '₦', name: 'Nigerian Naira' },
    { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling' },
    { code: 'GHS', symbol: '₵', name: 'Ghanaian Cedi' },
    { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling' },
    { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling' },
    { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha' },
    { code: 'BWP', symbol: 'P', name: 'Botswanan Pula' },
    { code: 'NAD', symbol: '$', name: 'Namibian Dollar' },
    { code: 'MUR', symbol: '₨', name: 'Mauritian Rupee' },
    { code: 'MZN', symbol: 'MT', name: 'Mozambican Metical' },
    { code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr' },
    { code: 'RWF', symbol: 'FRw', name: 'Rwandan Franc' },
    { code: 'SCR', symbol: '₨', name: 'Seychellois Rupee' },
    { code: 'SLL', symbol: 'Le', name: 'Sierra Leonean Leone' },
    { code: 'SOS', symbol: 'S', name: 'Somali Shilling' },
    { code: 'SDG', symbol: 'ج.س.', name: 'Sudanese Pound' },
    { code: 'LYD', symbol: 'ل.د', name: 'Libyan Dinar' },
    // Caribbean / Pacific / smaller currencies
    { code: 'FJD', symbol: '$', name: 'Fijian Dollar' },
    { code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina' },
    { code: 'SBD', symbol: '$', name: 'Solomon Islands Dollar' },
    { code: 'WST', symbol: 'WS$', name: 'Samoan Tala' },
    { code: 'TOP', symbol: 'T$', name: 'Tongan Paʻanga' },
    { code: 'VUV', symbol: 'VT', name: 'Vanuatu Vatu' },
    { code: 'BMD', symbol: '$', name: 'Bermudian Dollar' },
    { code: 'KYD', symbol: '$', name: 'Cayman Islands Dollar' },
    { code: 'AWG', symbol: 'ƒ', name: 'Aruban Florin' },
    { code: 'ANG', symbol: 'ƒ', name: 'Netherlands Antillean Guilder' },
    { code: 'GYD', symbol: '$', name: 'Guyanese Dollar' },
    { code: 'SRD', symbol: '$', name: 'Surinamese Dollar' },
    { code: 'HTG', symbol: 'G', name: 'Haitian Gourde' },
    { code: 'LSL', symbol: 'L', name: 'Lesotho Loti' },
    { code: 'SZL', symbol: 'E', name: 'Swazi Lilangeni' },
    { code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha' },
    { code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary' },
    { code: 'BIF', symbol: 'FBu', name: 'Burundian Franc' },
    { code: 'CDF', symbol: 'FC', name: 'Congolese Franc' },
    { code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc' },
    { code: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa' },
    { code: 'GMD', symbol: 'D', name: 'Gambian Dalasi' },
    { code: 'GNF', symbol: 'FG', name: 'Guinean Franc' },
    { code: 'KMF', symbol: 'CF', name: 'Comorian Franc' },
    { code: 'LRD', symbol: '$', name: 'Liberian Dollar' },
    { code: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa' },
    { code: 'MRO', symbol: 'UM', name: 'Mauritanian Ouguiya' },
    // Other supported currencies
    { code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum' },
    { code: 'CVE', symbol: '$', name: 'Cape Verdean Escudo' },
    { code: 'SHP', symbol: '£', name: 'Saint Helena Pound' },
    { code: 'FKP', symbol: '£', name: 'Falkland Islands Pound' },
    { code: 'GIP', symbol: '£', name: 'Gibraltar Pound' },
    { code: 'IMP', symbol: '£', name: 'Manx Pound' },
    { code: 'JEP', symbol: '£', name: 'Jersey Pound' },
    // Currency units / special entries supported by the API
    { code: 'XAF', symbol: 'FCFA', name: 'CFA Franc BEAC' },
    { code: 'XOF', symbol: 'CFA', name: 'CFA Franc BCEAO' },
    { code: 'XPF', symbol: '₣', name: 'CFP Franc' },
    { code: 'XDR', symbol: 'XDR', name: 'Special Drawing Rights' },
    { code: 'CLF', symbol: 'UF', name: 'Chilean Unit of Account' },
    { code: 'BTC', symbol: '₿', name: 'Bitcoin' },
    { code: 'XAU', symbol: 'Au', name: 'Gold' },
    { code: 'XAG', symbol: 'Ag', name: 'Silver' }
];